CREATE TABLE AUDIT_ENTRY(
  AUDIT_ENTRY_ID INT NOT NULL AUTO_INCREMENT,
  PROJECT VARCHAR(254) NOT NULL,
  USERNAME VARCHAR(254) NOT NULL,
  DOMAIN_NAME varchar(254)NOT NULL,
  TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  QUERY_TEXT TEXT,
  QUERY_TOPIC VARCHAR(245),
  PRIMARY KEY(AUDIT_ENTRY_ID),
  INDEX `IDX_AUDIT_ENTRY_DOMAIN_USERNAME_QUERY_TOPIC`(DOMAIN_NAME, USERNAME, QUERY_TOPIC)
)engine=innodb default charset=latin1;